/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package panduansoftice.view;

import javax.swing.ImageIcon;
import panduansoftice.template.ButtonImage;

/**
 *
 * @author zword
 */
public class FormTentang extends javax.swing.JInternalFrame {
    FormDisplay display;
    FormUtama fu;
    /**
     * Creates new form FormInstalasi
     */
    public FormTentang(FormUtama fu) {
        initComponents();
        this.fu = fu;  
                
        this.setRootPaneCheckingEnabled(false);
        javax.swing.plaf.InternalFrameUI ifu= this.getUI();
((javax.swing.plaf.basic.BasicInternalFrameUI)ifu).setNorthPane(null);
        
        buttonImage1.setImage(new ImageIcon(getClass().getResource("/panduansoftice/picture/TentangSoftice.jpg")).getImage());


    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        buttonImage1 = new panduansoftice.template.ButtonImage();

        setPreferredSize(new java.awt.Dimension(750, 420));

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("LinuxSoftice adalah sebuah \nSistem Operasi yang dibangun dengan menggunakan sistem \nlinux yang berlisensi Free and Open Source (FFOS). Linux \nsoftice dibuat dan didesain \nuntuk menyediakan Sistem \nOperasi yang bisa digunakan \nsecara gratis dan legal untuk dunia pemerintahan dan \nperkantoran. Tujuan lain dari \ndibuatnya LinuxSoftice adalah, mengurangi pembajakan \nsoftware yang sudah marak \nterjadi di Indonesia. \nLinuSoftice bisa diunduh \nsecara gratis melalui website \nlinuxsoftice.web.id, \nPengembang dari LinuxSoftice adalah anggota dari \nkomunitas yang bergerak \npada bidang open source, \nyaitu DOSCOM(Dinus Open \nSource Community) dengan \nseorang anggota dari \nDepkominfo (Darto Iwan \nSetiawan).LinuxSoftice dibuat \ndengan sukarela karena \nkeperdulian terhadap Negara \nIndonesia. Dengan donasilah \nyang bisa membuat kami \nterus berkembang untuk \ndapat memberikan fasilitas \nyang dibutuhkan oleh \npemerintah. Dan masukan- \nmasukan dan saran2 dapat \npengguna sampaikan melaui \nlinuxsoftice@gmail.com");
        jScrollPane1.setViewportView(jTextArea1);

        jButton3.setText("Kembali");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 23, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        fu.toPanduan();
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private panduansoftice.template.ButtonImage buttonImage1;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
